language: objective-c
osx_image: xcode8
sudo: false
git:
  submodules: false
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"          SCHEME="CoreStore iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="YES" RUN_DEMO="YES"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="CoreStore iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO" RUN_DEMO="YES"
# iOS 8 testing currently broken on Xcode 8
#    - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="CoreStore iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO" RUN_DEMO="YES"
#    - DESTINATION="OS=8.3,name=iPhone 5s"          SCHEME="CoreStore iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO" RUN_DEMO="YES"
#    - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="CoreStore iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO" RUN_DEMO="YES"
#    - DESTINATION="OS=8.1,name=iPhone 4s"          SCHEME="CoreStore iOS"     SDK=iphonesimulator10.0  RUN_TESTS="YES" POD_LINT="NO" RUN_DEMO="YES"
    - DESTINATION="arch=x86_64"                    SCHEME="CoreStore OSX"     SDK=macosx10.12          RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="CoreStore watchOS" SDK=watchsimulator3.0    RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=2.2,name=Apple Watch - 42mm" SCHEME="CoreStore watchOS" SDK=watchsimulator3.0    RUN_TESTS="NO"  POD_LINT="NO"
    - DESTINATION="OS=9.2,name=Apple TV 1080p"     SCHEME="CoreStore tvOS"    SDK=appletvsimulator10.0 RUN_TESTS="YES" POD_LINT="NO"
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"
before_script:
  - carthage update --use-submodules
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - if [ $RUN_TESTS == "YES" ]; then 
      xcodebuild -workspace CoreStore.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c;
      xcodebuild -workspace CoreStore.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean test | xcpretty -c;
    fi
  - if [ $RUN_DEMO == "YES" ]; then
      xcodebuild -project "CoreStoreDemo/CoreStoreDemo.xcodeproj" -target "CoreStoreDemo" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c;
      xcodebuild -project "CoreStoreDemo/CoreStoreDemo.xcodeproj" -target "CoreStoreDemo" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c;
    fi
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
