# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoreStore
email: rommel.estropia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Unleashing the real power of Core Data with the elegance and safety of Swift
baseurl: "/CoreStore" # the subpath of your site, e.g. /blog
url: "http://JohnEstropia.github.io/" # the base hostname & protocol for your site
twitter_username: JohnEstropia
github_username:  JohnEstropia

# Build settings
markdown: kramdown
